acme_hello_homepage:
    pattern:  /zdravo/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:index }
    
acme_new_page:
    pattern: /new/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:new }
    
acme_nenad_page:
    pattern:  /nenad/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:new }
    
acme_default_page:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }
