acme_form_homepage:
    pattern:  /form/
    defaults: { _controller: AcmeTaskBundle:Default:new }

acme_build_page:
    pattern:  /autobuild/
    defaults: { _controller: AcmeTaskBundle:Default:build }
    
acme_service_page:
    pattern:  /service/
    defaults: { _controller: AcmeTaskBundle:Default:service }